package com.etoak.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.18
 * 2020-06-01T11:23:34.194+08:00
 * Generated source version: 3.1.18
 * 
 */
@WebServiceClient(name = "UserviceService", 
                  wsdlLocation = "http://localhost:8080/ws/user?wsdl",
                  targetNamespace = "http://service.etoak.com/") 
public class UserviceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.etoak.com/", "UserviceService");
    public final static QName UservicePort = new QName("http://service.etoak.com/", "UservicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws/user?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserviceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws/user?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserviceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserviceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UserviceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserviceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Uservice
     */
    @WebEndpoint(name = "UservicePort")
    public Uservice getUservicePort() {
        return super.getPort(UservicePort, Uservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Uservice
     */
    @WebEndpoint(name = "UservicePort")
    public Uservice getUservicePort(WebServiceFeature... features) {
        return super.getPort(UservicePort, Uservice.class, features);
    }

}
